"use client";

import { useState } from "react";

type FaqItem = {
  question: string;
  answer: string;
};

type FaqProps = {
  items: FaqItem[];
};

export function Faq({ items }: FaqProps) {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <div className="faq">
      {items.map((item, index) => {
        const isOpen = openIndex === index;
        return (
          <div
            key={item.question}
            className={`faq-item reveal${isOpen ? " open" : ""}`}
          >
            <button
              className="faq-q"
              type="button"
              aria-expanded={isOpen}
              onClick={() => setOpenIndex(isOpen ? null : index)}
            >
              {item.question}
            </button>
            <div
              className="faq-a"
              style={{ maxHeight: isOpen ? "500px" : undefined }}
            >
              <div className="faq-a-inner">
                <p>{item.answer}</p>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}

export const homeFaqItems: FaqItem[] = [
  {
    question: "What happens on the first conversation?",
    answer:
      "A 30-minute conversation with no pitch deck. We ask about your current position, where AI is already in use, and what is prompting the question, whether that is an inspection, an audit, an insurer, or an enterprise buyer. You leave with a clear sense of whether we can help and what a sensible next step looks like. There is no commitment to continue.",
  },
  {
    question: "How are you different from a compliance software platform?",
    answer:
      "Software platforms collect evidence and monitor controls. We are the people who decide what good looks like for your specific use of AI, build the governance around it, and own the parts that automation cannot. We work alongside whatever tools you already run rather than replacing them.",
  },
  {
    question: "Do you work with schools and multi-academy trusts?",
    answer:
      "Yes. The education sector is a core focus. We align governance with DfE expectations, Keeping Children Safe in Education, and UK GDPR, and we size the work to the organisation, so a single-form-entry primary is not sold the same engagement as a 4,000-pupil trust.",
  },
  {
    question: "How long does an engagement take?",
    answer:
      "It depends on the size of your AI estate and the frameworks that apply. Discovery and a first defensible position are usually a matter of weeks, not months. We scope it precisely after the first conversation so you know the shape of the work before you commit.",
  },
  {
    question: "What if our AI policy was generated by AI itself?",
    answer:
      "That is more common than people admit, and it is exactly the kind of governance that does not survive an auditor's questions. We can review what you have, find where it falls short of your real AI use, and rebuild it into something defensible.",
  },
];
